#define LED_PIN 	26
#define LED_COUNT 	64

#define WEBSOCKET_URL "laravel.royoosterlee.nl"
#define WEBSOCKET_PORT 443

// #define SOCKETIO_SSL // UNCOMMENT IF CONNECTING TO DEFAULT WEBSOCKET
#define TEST_UBG // COMMENT IF CONNECTING TO DEFAULT WEBSOCKET

#ifdef TEST_UBG

// CHANGE THIS FOR LOCAL DEVELOPMENT
#define TEST_GAME GAME_VIEROPEENRIJ
#define TEST_WS_URL "192.168.1.120"
#define TEST_WS_PORT 8000


#endif


#define DEBUG_WEBSOCKETS