#define LED_PIN 	26
#define LED_COUNT 	64

#define WEBSOCKET_URL "laravel.royoosterlee.nl"
#define WEBSOCKET_PORT 443

#define SOCKETIO_SSL true // UNCOMMENT IF CONNECTING TO DEFAULT WEBSOCKET
// #define TEST_UBG // COMMENT IF CONNECTING TO DEFAULT WEBSOCKET

#ifdef TEST_UBG
// #define TEST_NO_SIO
// CHANGE THIS FOR LOCAL DEVELOPMENT
#define TEST_GAME GAME_NONE // Game to test one of: [GAME_VIEROPEENRIJ, GAME_THIRTYSECONDS, GAME_TRIVIALPURSUIT, GAME_VLOTTEGEESTEN, GAME_GANZENBORD]
#define TEST_WS_URL "" // IP address of computer here (eg. 192.168.1.123)
#define TEST_WS_PORT 8080


#endif


// #define DEBUG_WEBSOCKETS(...) Serial.printf( __VA_ARGS__ )